import {Actor} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";

const font = Actor({subsets: ["latin"], weight: '400'});

export const metadata = {
    title: {
        template: '%s | Nextjs Darija',
        default: 'Nextjs darija',
    },
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={cn('dark', font.className)}>
        <section className={'my-4 '}>
            {children}
        </section>
        </body>
        </html>
    );
}
