import {Actor} from "next/font/google";
import "./globals.css";
import MenuBar from "@/components/MenuBar";

const font = Actor({subsets: ["latin"], weight: '400'});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={font.className}>
        <MenuBar/>
        <section className={'my-4'}>
            {children}
        </section>
        <footer className={'bg-slate-900 text-white text-center'}>
            &copy; {new Date().getFullYear()}
        </footer>
        </body>
        </html>
    );
}
